# Copyright 2024 Nir Lisker
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Package

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating System"
        required: true
        type: choice
        options:
          - '["ubuntu", "macos", "windows"]'
          - '["windows"]'
          - '["macos"]'
          - '["ubuntu"]'
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    outputs:
      version:
        description: "The version number"
        value: ${{ jobs.package.outputs.version }}
      artifact_name:
        description: "The zipped image file name"
        value: ${{ jobs.package.outputs.artifact_name }}

jobs:
  package:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
      artifact_name: ${{ steps.naming.outputs.artifact_name }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          22
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable on Linux/MacOS
      if: runner.os != 'Windows'
      run: chmod +x ./gradlew

    - name: Create version variable
      id: versioning
      run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

    - name: Create artifact name
      id: naming
      run: echo "artifact_name=jextractGUI-${{ steps.versioning.outputs.version }}-${{ matrix.os }}-x64.zip" >> $GITHUB_OUTPUT

    - name: Create zipped jpackage image
      run: ./gradlew jpackageImageZip

    - name: Upload zipped image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.naming.outputs.artifact_name }}
        path: build/jextractGUI*.zip
        if-no-files-found: error
        retention-days: 1