name: Package

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating System"
        required: true
        type: choice
        options:
          - '["ubuntu", "macos", "windows"]'
          - '["windows"]'
          - '["macos"]'
          - '["ubuntu"]'
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  package:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          22
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable on Linux/MacOS
      if: runner.os != 'Windows'
      run: chmod +x ./gradlew

    - name: Create zipped jpackage image
      run: ./gradlew jpackageImageZip

    - name: Upload zipped image
      uses: actions/upload-artifact@v4
      with:
        name: jextractGUI-${{ matrix.os }}-x64.zip
        path: build/jextractGUI*.zip
        if-no-files-found: error
        retention-days: 1