name: Package

on: push #workflow_dispatch

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          22
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable on Linux/MacOS
      if: runner.os != 'Windows'
      run: chmod +x ./gradlew

    - name: Create jpackage image
      run: ./gradlew jpackageImage

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: jextractGUI-${{ matrix.os }}
        path: build/jpackage/jextractGUI*