name: Package

on: push # workflow_dispatch

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu, windows] #macos
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          22
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable on Linux/MacOS
      if: runner.os != 'Windows'
      run: chmod +x ./gradlew

    - name: Create a zipped jpackage image
      run: ./gradlew jpackageImageZip

    - name: Upload to release
      uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action
      with:
        artifacts: build/jextractGUI-${{ matrix.os }}-x64.zip
        generateReleaseNotes: true
        tag: v1.0.0-shapshot
        allowUpdates: true