name: Release

on: [
  push,
  workflow_dispatch
  ]

jobs:
  package:
    uses: ./.github/workflows/package.yaml
  release:
    strategy:
      matrix:
        os: [ubuntu] #, windows] macos
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    needs: [package]
    steps:
    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: jextractGUI-${{ matrix.os }}-x64.zip
        path: build

    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload to release
      uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action
      with:
        artifacts: build/jextractGUI-${{ matrix.os }}-x64.zip
        generateReleaseNotes: true
        tag: v1.0.1-shapshot
        allowUpdates: true
        draft: true
        artifactErrorsFailBuild: true