# Copyright 2024 Nir Lisker
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating System"
        required: true
        type: choice
        options:
          - '["ubuntu", "macos", "windows"]'
          - '["windows"]'
          - '["macos"]'
          - '["ubuntu"]'

jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      os: ${{ inputs.os }}

  release:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    needs: [package]
    steps:
    - name: Download zipped image
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.package.outputs.artifact_name }}

    - name: Print content
      run: ls -R

    - name: Upload to release
      uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action
      with:
        artifacts: ${{ needs.package.outputs.artifact_name }}
        tag: "v${{ needs.package.outputs.version }}"
        generateReleaseNotes: true
        allowUpdates: true
        draft: true
        artifactErrorsFailBuild: true

    - name: Print result
      run: echo "Released ${{ needs.package.outputs.artifact_name }} to v${{ needs.package.outputs.version }}"